version: "3.9"
services:
  ow-league-tokens:
    volumes: ['./src/profiles:/app/src/profiles']
    build: .
    environment:
      PASSWORD: CHANGE_ME!
    entrypoint: ['/bin/sh', '-c', './docker-entrypoint.sh']
    ports:
      - 5900:5900
    restart: unless-stopped
